apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-examples.fullname" . }}-rates
spec:
  type: {{ .Values.rates_service.service.type }}
  selector:
    app: rates
  ports:
    - protocol: TCP
      port: {{ .Values.rates_service.service.port }}
